/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

/**
 *
 * @author user
 */
public class Departamento extends javax.swing.JDialog {

    /**
     * Creates new form Departamento
     */
    public Departamento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblCrearDepartamento = new javax.swing.JLabel();
        lblEliminarDepartamento = new javax.swing.JLabel();
        lblActualizarDepartamento = new javax.swing.JLabel();
        lblMostrarDepartamento = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnCrearDepartamento = new javax.swing.JButton();
        btnEliminarDepartamento = new javax.swing.JButton();
        btnActualizarDepartamento = new javax.swing.JButton();
        btnMostrarDepartamento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(698, 463));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(86, 130, 241));

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Departamento Compuwork");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel4)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblCrearDepartamento.setForeground(new java.awt.Color(0, 0, 0));
        lblCrearDepartamento.setText("Crear Departamento");

        lblEliminarDepartamento.setForeground(new java.awt.Color(0, 0, 0));
        lblEliminarDepartamento.setText("Eliminar Departamento");

        lblActualizarDepartamento.setForeground(new java.awt.Color(0, 0, 0));
        lblActualizarDepartamento.setText("Actualizar Departamento");

        lblMostrarDepartamento.setForeground(new java.awt.Color(0, 0, 0));
        lblMostrarDepartamento.setText("Mostrar Departamento");

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(0, 0, 0));
        btnVolver.setText("Volver");
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });

        btnCrearDepartamento.setBackground(new java.awt.Color(255, 255, 255));
        btnCrearDepartamento.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btnCrearDepartamento.setForeground(new java.awt.Color(0, 0, 0));
        btnCrearDepartamento.setText("Crear");
        btnCrearDepartamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearDepartamentoMouseClicked(evt);
            }
        });

        btnEliminarDepartamento.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminarDepartamento.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btnEliminarDepartamento.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarDepartamento.setText("Eliminar");
        btnEliminarDepartamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarDepartamentoMouseClicked(evt);
            }
        });

        btnActualizarDepartamento.setBackground(new java.awt.Color(255, 255, 255));
        btnActualizarDepartamento.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btnActualizarDepartamento.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizarDepartamento.setText("Actualizar");
        btnActualizarDepartamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarDepartamentoMouseClicked(evt);
            }
        });

        btnMostrarDepartamento.setBackground(new java.awt.Color(255, 255, 255));
        btnMostrarDepartamento.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btnMostrarDepartamento.setForeground(new java.awt.Color(0, 0, 0));
        btnMostrarDepartamento.setText("Mostrar");
        btnMostrarDepartamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarDepartamentoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(106, 106, 106))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCrearDepartamento)
                    .addComponent(lblEliminarDepartamento)
                    .addComponent(lblActualizarDepartamento)
                    .addComponent(lblMostrarDepartamento))
                .addGap(87, 87, 87)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMostrarDepartamento)
                    .addComponent(btnActualizarDepartamento)
                    .addComponent(btnEliminarDepartamento)
                    .addComponent(btnCrearDepartamento))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCrearDepartamento)
                    .addComponent(btnCrearDepartamento))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEliminarDepartamento)
                    .addComponent(btnEliminarDepartamento))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblActualizarDepartamento)
                    .addComponent(btnActualizarDepartamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMostrarDepartamento)
                    .addComponent(btnMostrarDepartamento))
                .addGap(22, 22, 22)
                .addComponent(btnVolver)
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnCrearDepartamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearDepartamentoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearDepartamentoMouseClicked

    private void btnEliminarDepartamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarDepartamentoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarDepartamentoMouseClicked

    private void btnActualizarDepartamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarDepartamentoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarDepartamentoMouseClicked

    private void btnMostrarDepartamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarDepartamentoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarDepartamentoMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarDepartamento;
    private javax.swing.JButton btnCrearDepartamento;
    private javax.swing.JButton btnEliminarDepartamento;
    private javax.swing.JButton btnMostrarDepartamento;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblActualizarDepartamento;
    private javax.swing.JLabel lblCrearDepartamento;
    private javax.swing.JLabel lblEliminarDepartamento;
    private javax.swing.JLabel lblMostrarDepartamento;
    // End of variables declaration//GEN-END:variables
}
