/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;
import controller.Controlador;
import javax.swing.JOptionPane;
import model.Empleado;
import model.Temporal;
/**
 *
 * @author user
 */
public class EmpleadoControlador extends javax.swing.JDialog {
    private EmpleadoControlador empleado;
    private Controlador controlador;
    private Empleado empleadop;
    /**
     * Creates new form Empleado
     */
    public EmpleadoControlador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.controlador = new Controlador();
        this.setLocationRelativeTo(null);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panelAPermanencia = new javax.swing.JTabbedPane();
        panelIngresar = new javax.swing.JPanel();
        lblNombreEmpleado = new javax.swing.JLabel();
        lblCargoEmpleado = new javax.swing.JLabel();
        lblCorreoEmpleado = new javax.swing.JLabel();
        btnCrearEmpleado = new javax.swing.JButton();
        lblApellidoEmpleado = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCargo = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        lblNombreEmpleado1 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        lblApellidoEmpleado1 = new javax.swing.JLabel();
        txtApellido1 = new javax.swing.JTextField();
        lblCargoEmpleado1 = new javax.swing.JLabel();
        txtCargo1 = new javax.swing.JTextField();
        txtCorreo1 = new javax.swing.JTextField();
        lblCorreoEmpleado1 = new javax.swing.JLabel();
        btnCrearEmpleadoTemporal = new javax.swing.JButton();
        lblFechaInicio = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JTextField();
        lblFechaFin = new javax.swing.JLabel();
        txtFechaFin = new javax.swing.JTextField();
        panelActualizar = new javax.swing.JPanel();
        lblNombreEmpleado2 = new javax.swing.JLabel();
        lblCargoEmpleado2 = new javax.swing.JLabel();
        lblCorreoEmpleado2 = new javax.swing.JLabel();
        btnActualizarEmpleado = new javax.swing.JButton();
        lblApellidoEmpleado2 = new javax.swing.JLabel();
        txtNombre2 = new javax.swing.JTextField();
        txtApellido2 = new javax.swing.JTextField();
        txtCargo2 = new javax.swing.JTextField();
        txtCorreo2 = new javax.swing.JTextField();
        lblIDEmpleado = new javax.swing.JLabel();
        txtIDActualizar = new javax.swing.JTextField();
        panelEliminar = new javax.swing.JPanel();
        btnEliminarEmpleado = new javax.swing.JButton();
        lblIDEmpleadoEliminar = new javax.swing.JLabel();
        txtIDEmpleadoEliminar = new javax.swing.JTextField();
        lblIDEmpleadoT = new javax.swing.JLabel();
        txtIDEliminarEmpleadoTemporal = new javax.swing.JTextField();
        btnEliminarEmpleadoT = new javax.swing.JButton();
        panelMostrar = new javax.swing.JPanel();
        btnMostrarEmpleados = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMostrarEmpleadosP = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMostrarEmpleadosT = new javax.swing.JTextPane();
        lblMostrarEmpleadosP = new javax.swing.JLabel();
        lblMostrarEmpleadosT = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblIDEmpleadoAPermanencia = new javax.swing.JLabel();
        txtIDActualizaPermanencia = new javax.swing.JTextField();
        btnActualizaPermanencia = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(86, 130, 241));

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Empleados Compuwork");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel4)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        panelAPermanencia.setBackground(new java.awt.Color(86, 130, 241));
        panelAPermanencia.setForeground(new java.awt.Color(255, 255, 255));
        panelAPermanencia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        panelIngresar.setBackground(new java.awt.Color(255, 255, 255));

        lblNombreEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreEmpleado.setText("Nombre :");

        lblCargoEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        lblCargoEmpleado.setText("Cargo :");

        lblCorreoEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        lblCorreoEmpleado.setText("Correo :");

        btnCrearEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        btnCrearEmpleado.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btnCrearEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        btnCrearEmpleado.setText("Ingresar");
        btnCrearEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearEmpleadoMouseClicked(evt);
            }
        });
        btnCrearEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearEmpleadoActionPerformed(evt);
            }
        });

        lblApellidoEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        lblApellidoEmpleado.setText("Apellido :");

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtApellido.setBackground(new java.awt.Color(255, 255, 255));
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });

        txtCargo.setBackground(new java.awt.Color(255, 255, 255));
        txtCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCargoActionPerformed(evt);
            }
        });

        txtCorreo.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        lblNombreEmpleado1.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreEmpleado1.setText("Nombre :");

        txtNombre1.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre1ActionPerformed(evt);
            }
        });

        lblApellidoEmpleado1.setForeground(new java.awt.Color(0, 0, 0));
        lblApellidoEmpleado1.setText("Apellido :");

        txtApellido1.setBackground(new java.awt.Color(255, 255, 255));
        txtApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellido1ActionPerformed(evt);
            }
        });

        lblCargoEmpleado1.setForeground(new java.awt.Color(0, 0, 0));
        lblCargoEmpleado1.setText("Cargo :");

        txtCargo1.setBackground(new java.awt.Color(255, 255, 255));
        txtCargo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCargo1ActionPerformed(evt);
            }
        });

        txtCorreo1.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreo1ActionPerformed(evt);
            }
        });

        lblCorreoEmpleado1.setForeground(new java.awt.Color(0, 0, 0));
        lblCorreoEmpleado1.setText("Correo :");

        btnCrearEmpleadoTemporal.setBackground(new java.awt.Color(255, 255, 255));
        btnCrearEmpleadoTemporal.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btnCrearEmpleadoTemporal.setForeground(new java.awt.Color(0, 0, 0));
        btnCrearEmpleadoTemporal.setText("Ingresar temporal");
        btnCrearEmpleadoTemporal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearEmpleadoTemporalMouseClicked(evt);
            }
        });
        btnCrearEmpleadoTemporal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearEmpleadoTemporalActionPerformed(evt);
            }
        });

        lblFechaInicio.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaInicio.setText("Fecha incio");

        txtFechaInicio.setBackground(new java.awt.Color(255, 255, 255));
        txtFechaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaInicioActionPerformed(evt);
            }
        });

        lblFechaFin.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaFin.setText("Fecha fin");

        txtFechaFin.setBackground(new java.awt.Color(255, 255, 255));
        txtFechaFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaFinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelIngresarLayout = new javax.swing.GroupLayout(panelIngresar);
        panelIngresar.setLayout(panelIngresarLayout);
        panelIngresarLayout.setHorizontalGroup(
            panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresarLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIngresarLayout.createSequentialGroup()
                        .addGroup(panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreEmpleado)
                            .addComponent(lblCargoEmpleado))
                        .addGap(40, 40, 40)
                        .addGroup(panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelIngresarLayout.createSequentialGroup()
                                .addComponent(lblCorreoEmpleado)
                                .addGap(26, 26, 26)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                            .addGroup(panelIngresarLayout.createSequentialGroup()
                                .addComponent(lblApellidoEmpleado)
                                .addGap(18, 18, 18)
                                .addComponent(txtApellido))))
                    .addGroup(panelIngresarLayout.createSequentialGroup()
                        .addGroup(panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelIngresarLayout.createSequentialGroup()
                                .addGroup(panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreEmpleado1)
                                    .addComponent(lblCargoEmpleado1))
                                .addGap(40, 40, 40)
                                .addGroup(panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCargo1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblFechaInicio))
                        .addGap(64, 64, 64)
                        .addGroup(panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelIngresarLayout.createSequentialGroup()
                                .addComponent(lblCorreoEmpleado1)
                                .addGap(26, 26, 26)
                                .addComponent(txtCorreo1))
                            .addGroup(panelIngresarLayout.createSequentialGroup()
                                .addComponent(lblApellidoEmpleado1)
                                .addGap(18, 18, 18)
                                .addComponent(txtApellido1))
                            .addGroup(panelIngresarLayout.createSequentialGroup()
                                .addComponent(lblFechaFin)
                                .addGap(26, 26, 26)
                                .addComponent(txtFechaFin)))))
                .addGap(123, 123, 123))
            .addGroup(panelIngresarLayout.createSequentialGroup()
                .addGroup(panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIngresarLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(btnCrearEmpleado))
                    .addGroup(panelIngresarLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btnCrearEmpleadoTemporal)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelIngresarLayout.setVerticalGroup(
            panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreEmpleado)
                    .addComponent(lblApellidoEmpleado)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCargoEmpleado)
                    .addComponent(lblCorreoEmpleado)
                    .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btnCrearEmpleado)
                .addGap(36, 36, 36)
                .addGroup(panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreEmpleado1)
                    .addComponent(lblApellidoEmpleado1)
                    .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCargoEmpleado1)
                    .addComponent(lblCorreoEmpleado1)
                    .addComponent(txtCargo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaInicio)
                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaFin)
                    .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCrearEmpleadoTemporal)
                .addGap(77, 77, 77))
        );

        panelAPermanencia.addTab("Ingresar", panelIngresar);

        panelActualizar.setBackground(new java.awt.Color(255, 255, 255));

        lblNombreEmpleado2.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreEmpleado2.setText("Nombre :");

        lblCargoEmpleado2.setForeground(new java.awt.Color(0, 0, 0));
        lblCargoEmpleado2.setText("Cargo :");

        lblCorreoEmpleado2.setForeground(new java.awt.Color(0, 0, 0));
        lblCorreoEmpleado2.setText("Correo :");

        btnActualizarEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        btnActualizarEmpleado.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btnActualizarEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizarEmpleado.setText("Actualizar");
        btnActualizarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarEmpleadoMouseClicked(evt);
            }
        });
        btnActualizarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarEmpleadoActionPerformed(evt);
            }
        });

        lblApellidoEmpleado2.setForeground(new java.awt.Color(0, 0, 0));
        lblApellidoEmpleado2.setText("Apellido :");

        txtNombre2.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre2ActionPerformed(evt);
            }
        });

        txtApellido2.setBackground(new java.awt.Color(255, 255, 255));
        txtApellido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellido2ActionPerformed(evt);
            }
        });

        txtCargo2.setBackground(new java.awt.Color(255, 255, 255));
        txtCargo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCargo2ActionPerformed(evt);
            }
        });

        txtCorreo2.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreo2ActionPerformed(evt);
            }
        });

        lblIDEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        lblIDEmpleado.setText("Ingresar el ID del empleado a actualizar :");

        txtIDActualizar.setBackground(new java.awt.Color(255, 255, 255));
        txtIDActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelActualizarLayout = new javax.swing.GroupLayout(panelActualizar);
        panelActualizar.setLayout(panelActualizarLayout);
        panelActualizarLayout.setHorizontalGroup(
            panelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActualizarLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(panelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActualizarLayout.createSequentialGroup()
                        .addGroup(panelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreEmpleado2)
                            .addComponent(lblCargoEmpleado2))
                        .addGap(40, 40, 40)
                        .addGroup(panelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCargo2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(panelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelActualizarLayout.createSequentialGroup()
                                .addComponent(lblCorreoEmpleado2)
                                .addGap(26, 26, 26)
                                .addComponent(txtCorreo2))
                            .addGroup(panelActualizarLayout.createSequentialGroup()
                                .addComponent(lblApellidoEmpleado2)
                                .addGap(18, 18, 18)
                                .addComponent(txtApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelActualizarLayout.createSequentialGroup()
                        .addGroup(panelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelActualizarLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(lblIDEmpleado)
                                .addGap(26, 26, 26)
                                .addComponent(txtIDActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnActualizarEmpleado))
                        .addGap(141, 141, 141)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        panelActualizarLayout.setVerticalGroup(
            panelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActualizarLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(panelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDEmpleado)
                    .addComponent(txtIDActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreEmpleado2)
                    .addComponent(lblApellidoEmpleado2)
                    .addComponent(txtNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCargoEmpleado2)
                    .addComponent(lblCorreoEmpleado2)
                    .addComponent(txtCargo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(btnActualizarEmpleado)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        panelAPermanencia.addTab("Actualizar", panelActualizar);

        panelEliminar.setBackground(new java.awt.Color(255, 255, 255));

        btnEliminarEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminarEmpleado.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btnEliminarEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarEmpleado.setText("Eliminar");
        btnEliminarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarEmpleadoMouseClicked(evt);
            }
        });
        btnEliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEmpleadoActionPerformed(evt);
            }
        });

        lblIDEmpleadoEliminar.setForeground(new java.awt.Color(0, 0, 0));
        lblIDEmpleadoEliminar.setText("Ingresar el ID del empleado a eliminar :");

        txtIDEmpleadoEliminar.setBackground(new java.awt.Color(255, 255, 255));
        txtIDEmpleadoEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDEmpleadoEliminarActionPerformed(evt);
            }
        });

        lblIDEmpleadoT.setForeground(new java.awt.Color(0, 0, 0));
        lblIDEmpleadoT.setText("Ingresar el ID del empleado temporal a eliminar :");

        txtIDEliminarEmpleadoTemporal.setBackground(new java.awt.Color(255, 255, 255));
        txtIDEliminarEmpleadoTemporal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDEliminarEmpleadoTemporalActionPerformed(evt);
            }
        });

        btnEliminarEmpleadoT.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminarEmpleadoT.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btnEliminarEmpleadoT.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarEmpleadoT.setText("Eliminar Temporal");
        btnEliminarEmpleadoT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarEmpleadoTMouseClicked(evt);
            }
        });
        btnEliminarEmpleadoT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEmpleadoTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEliminarLayout = new javax.swing.GroupLayout(panelEliminar);
        panelEliminar.setLayout(panelEliminarLayout);
        panelEliminarLayout.setHorizontalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelEliminarLayout.createSequentialGroup()
                        .addComponent(lblIDEmpleadoEliminar)
                        .addGap(26, 26, 26)
                        .addComponent(txtIDEmpleadoEliminar))
                    .addGroup(panelEliminarLayout.createSequentialGroup()
                        .addComponent(lblIDEmpleadoT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIDEliminarEmpleadoTemporal, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63)
                .addGroup(panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminarEmpleadoT)
                    .addGroup(panelEliminarLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnEliminarEmpleado)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        panelEliminarLayout.setVerticalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEliminarLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDEmpleadoEliminar)
                    .addComponent(txtIDEmpleadoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarEmpleado))
                .addGap(45, 45, 45)
                .addGroup(panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDEmpleadoT)
                    .addComponent(txtIDEliminarEmpleadoTemporal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarEmpleadoT))
                .addContainerGap(272, Short.MAX_VALUE))
        );

        panelAPermanencia.addTab("Eliminar", panelEliminar);

        panelMostrar.setBackground(new java.awt.Color(255, 255, 255));

        btnMostrarEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        btnMostrarEmpleados.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btnMostrarEmpleados.setForeground(new java.awt.Color(0, 0, 0));
        btnMostrarEmpleados.setText("Mostrar");
        btnMostrarEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarEmpleadosMouseClicked(evt);
            }
        });
        btnMostrarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarEmpleadosActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        txtMostrarEmpleadosP.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(txtMostrarEmpleadosP);

        txtMostrarEmpleadosT.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(txtMostrarEmpleadosT);

        lblMostrarEmpleadosP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMostrarEmpleadosP.setForeground(new java.awt.Color(0, 0, 0));
        lblMostrarEmpleadosP.setText("Empleados permanentes");

        lblMostrarEmpleadosT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMostrarEmpleadosT.setForeground(new java.awt.Color(0, 0, 0));
        lblMostrarEmpleadosT.setText("Empleados temporales");

        javax.swing.GroupLayout panelMostrarLayout = new javax.swing.GroupLayout(panelMostrar);
        panelMostrar.setLayout(panelMostrarLayout);
        panelMostrarLayout.setHorizontalGroup(
            panelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMostrarLayout.createSequentialGroup()
                .addGroup(panelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMostrarLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnMostrarEmpleados))
                    .addGroup(panelMostrarLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(panelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMostrarEmpleadosP))
                        .addGap(65, 65, 65)
                        .addGroup(panelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMostrarEmpleadosT)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panelMostrarLayout.setVerticalGroup(
            panelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMostrarLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(panelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMostrarEmpleadosP, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMostrarEmpleadosT, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(panelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(btnMostrarEmpleados)
                .addGap(50, 50, 50))
        );

        panelAPermanencia.addTab("Mostar", panelMostrar);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblIDEmpleadoAPermanencia.setForeground(new java.awt.Color(0, 0, 0));
        lblIDEmpleadoAPermanencia.setText("Ingresar el ID del empleado a actualizar Permanencia :");

        txtIDActualizaPermanencia.setBackground(new java.awt.Color(255, 255, 255));

        btnActualizaPermanencia.setBackground(new java.awt.Color(255, 255, 255));
        btnActualizaPermanencia.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btnActualizaPermanencia.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizaPermanencia.setText("Actualizar Permanencia");
        btnActualizaPermanencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizaPermanenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(lblIDEmpleadoAPermanencia)
                .addGap(18, 18, 18)
                .addComponent(txtIDActualizaPermanencia, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(btnActualizaPermanencia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDEmpleadoAPermanencia)
                    .addComponent(txtIDActualizaPermanencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                .addComponent(btnActualizaPermanencia)
                .addGap(92, 92, 92))
        );

        panelAPermanencia.addTab("Actualizar permanencia", jPanel3);

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(0, 0, 0));
        btnVolver.setText("Volver");
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAPermanencia, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(panelAPermanencia, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVolver)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarEmpleadosActionPerformed
        // TODO add your handling code here:
        txtMostrarEmpleadosP.setText(controlador.mostrarEmpleados());
        txtMostrarEmpleadosT.setText(controlador.mostrarEmpleadosT());
    }//GEN-LAST:event_btnMostrarEmpleadosActionPerformed

    private void btnMostrarEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarEmpleadosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarEmpleadosMouseClicked

    private void txtIDEmpleadoEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDEmpleadoEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDEmpleadoEliminarActionPerformed

    private void btnEliminarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarEmpleadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarEmpleadoMouseClicked

    private void txtIDActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActualizarActionPerformed

    private void txtCorreo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreo2ActionPerformed

    private void txtCargo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCargo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCargo2ActionPerformed

    private void txtApellido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellido2ActionPerformed

    private void txtNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre2ActionPerformed

    private void btnActualizarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarEmpleadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarEmpleadoMouseClicked

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCargoActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnCrearEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearEmpleadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearEmpleadoMouseClicked

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverMouseClicked

    private void txtNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre1ActionPerformed

    private void txtApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellido1ActionPerformed

    private void txtCargo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCargo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCargo1ActionPerformed

    private void txtCorreo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreo1ActionPerformed

    private void btnCrearEmpleadoTemporalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearEmpleadoTemporalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearEmpleadoTemporalMouseClicked

    private void txtFechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaInicioActionPerformed

    private void txtFechaFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaFinActionPerformed

    private void txtIDEliminarEmpleadoTemporalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDEliminarEmpleadoTemporalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDEliminarEmpleadoTemporalActionPerformed

    private void btnEliminarEmpleadoTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarEmpleadoTMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarEmpleadoTMouseClicked

    private void btnEliminarEmpleadoTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEmpleadoTActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(this.txtIDEliminarEmpleadoTemporal.getText());
            controlador.eliminarEmpleadoT(id);
            JOptionPane.showMessageDialog(this, "el empleado con id "+id+" ha sido eliminado existosamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "no se encontro el id ingresado");
        }
         txtIDEliminarEmpleadoTemporal.setText("");
    }//GEN-LAST:event_btnEliminarEmpleadoTActionPerformed

    private void btnActualizaPermanenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizaPermanenciaActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(this.txtIDActualizaPermanencia.getText());
            controlador.actualizarPermanencia(id);
            JOptionPane.showMessageDialog(this, "el empleado con id "+id+" ha sido actualizado existosamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "no se encontro el id ingresado");
        }
        txtIDActualizaPermanencia.setText("");
    }//GEN-LAST:event_btnActualizaPermanenciaActionPerformed

    private void btnEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEmpleadoActionPerformed
        // TODO add your handling code here:                           
        try {
            int id = Integer.parseInt(this.txtIDEmpleadoEliminar.getText());
            controlador.eliminarEmpleado(id);
            JOptionPane.showMessageDialog(this, "el empleado con id "+id+" ha sido eliminado existosamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "no se encontro el id ingresado");
        }
        
        txtIDEmpleadoEliminar.setText("");
    }//GEN-LAST:event_btnEliminarEmpleadoActionPerformed

    private void btnActualizarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarEmpleadoActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(this.txtIDActualizar.getText());
            Empleado empleadoActualizado = new Empleado(id, txtNombre2.getText(), txtApellido2.getText(), txtCargo2.getText(), txtCorreo2.getText(), false);
            controlador.actualizarEmpleado(id, empleadoActualizado);
            JOptionPane.showMessageDialog(this, "el empleado con id "+id+" ha sido actualizado existosamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "no se encontro el id ingresado");
        }
        
        txtNombre2.setText("");
        txtApellido2.setText("");
        txtCargo2.setText("");
        txtCorreo2.setText("");
        txtIDActualizar.setText("");
    }//GEN-LAST:event_btnActualizarEmpleadoActionPerformed

    private void btnCrearEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearEmpleadoActionPerformed
        // TODO add your handling code here:
        try {
            Empleado p = new Empleado( txtNombre.getText(), txtApellido.getText(), txtCargo.getText(), txtCorreo.getText(), true);
            this.controlador.agregarEmpleado(p);
            JOptionPane.showMessageDialog(this, "el empleado se ha agregado existosamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "no se pudo igresar el empleado intentarlo denuevo");
        }
        
        txtNombre.setText("");
        txtApellido.setText("");
        txtCargo.setText("");
        txtCorreo.setText("");
    }//GEN-LAST:event_btnCrearEmpleadoActionPerformed

    private void btnCrearEmpleadoTemporalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearEmpleadoTemporalActionPerformed
        // TODO add your handling code here:
        try {
            controlador.agregarEmpleado(new Temporal(txtNombre1.getText(), txtApellido1.getText(), txtCargo1.getText(), txtCorreo1.getText(),txtFechaInicio.getText(),txtFechaFin.getText()));    
            JOptionPane.showMessageDialog(this, "el empleado se ha agregado existosamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "no se pudo igresar el empleado intentarlo denuevo");
        }
        
        txtNombre1.setText("");
        txtApellido1.setText("");
        txtCargo1.setText("");
        txtCorreo1.setText("");
        txtFechaInicio.setText("");
        txtFechaFin.setText("");
    }//GEN-LAST:event_btnCrearEmpleadoTemporalActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizaPermanencia;
    private javax.swing.JButton btnActualizarEmpleado;
    private javax.swing.JButton btnCrearEmpleado;
    private javax.swing.JButton btnCrearEmpleadoTemporal;
    private javax.swing.JButton btnEliminarEmpleado;
    private javax.swing.JButton btnEliminarEmpleadoT;
    private javax.swing.JButton btnMostrarEmpleados;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblApellidoEmpleado;
    private javax.swing.JLabel lblApellidoEmpleado1;
    private javax.swing.JLabel lblApellidoEmpleado2;
    private javax.swing.JLabel lblCargoEmpleado;
    private javax.swing.JLabel lblCargoEmpleado1;
    private javax.swing.JLabel lblCargoEmpleado2;
    private javax.swing.JLabel lblCorreoEmpleado;
    private javax.swing.JLabel lblCorreoEmpleado1;
    private javax.swing.JLabel lblCorreoEmpleado2;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblIDEmpleado;
    private javax.swing.JLabel lblIDEmpleadoAPermanencia;
    private javax.swing.JLabel lblIDEmpleadoEliminar;
    private javax.swing.JLabel lblIDEmpleadoT;
    private javax.swing.JLabel lblMostrarEmpleadosP;
    private javax.swing.JLabel lblMostrarEmpleadosT;
    private javax.swing.JLabel lblNombreEmpleado;
    private javax.swing.JLabel lblNombreEmpleado1;
    private javax.swing.JLabel lblNombreEmpleado2;
    private javax.swing.JTabbedPane panelAPermanencia;
    private javax.swing.JPanel panelActualizar;
    private javax.swing.JPanel panelEliminar;
    private javax.swing.JPanel panelIngresar;
    private javax.swing.JPanel panelMostrar;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtCargo1;
    private javax.swing.JTextField txtCargo2;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtCorreo1;
    private javax.swing.JTextField txtCorreo2;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtIDActualizaPermanencia;
    private javax.swing.JTextField txtIDActualizar;
    private javax.swing.JTextField txtIDEliminarEmpleadoTemporal;
    private javax.swing.JTextField txtIDEmpleadoEliminar;
    private javax.swing.JTextPane txtMostrarEmpleadosP;
    private javax.swing.JTextPane txtMostrarEmpleadosT;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtNombre2;
    // End of variables declaration//GEN-END:variables
}
